import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { Check, CreditCard, Pencil, Plus, Tags, Trash2 } from 'lucide-react'
import { api, errorMessage } from '../api/client'
import type { Category, CategoryType, Frequency, Subscription } from '../api/types'
import { useAuth } from '../auth/AuthContext'
import { EmptyState, ErrorBox, Loading, PageTitle, money } from './shared'

function CategoryEditor({ initial, onSave, onCancel, busy }: { initial?: Category; onSave: (name: string, categoryType: CategoryType) => Promise<void>; onCancel: () => void; busy: boolean }) {
  const [name, setName] = useState(initial?.name ?? '')
  const [type, setType] = useState<CategoryType>(initial?.categoryType ?? 'EXIT')
  return <form className="edit-form" onSubmit={(event) => { event.preventDefault(); void onSave(name.trim(), type) }}><div className="form-grid"><label className="field"><span>Nome da categoria</span><input required maxLength={80} value={name} onChange={(event) => setName(event.target.value)} placeholder="Ex.: Moradia, transporte…" /></label><label className="field"><span>Tipo de movimentação</span><select value={type} onChange={(event) => setType(event.target.value as CategoryType)}><option value="ENTRY">Entrada</option><option value="EXIT">Despesa</option><option value="BOTH">Entrada e despesa</option></select></label></div><div className="form-actions"><button type="button" className="button button-quiet" onClick={onCancel}>Cancelar</button><button className="button button-primary" disabled={busy}>{busy ? 'Salvando…' : initial ? 'Salvar categoria' : 'Criar categoria'}</button></div></form>
}

export function CategoriesPage() {
  const [categories, setCategories] = useState<Category[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [editing, setEditing] = useState<Category | 'new' | null>(null)
  const [busy, setBusy] = useState(false)
  const load = useCallback(async () => { setLoading(true); try { const { data } = await api.get<Category[]>('/api/category/categoriesList'); setCategories(data); setError('') } catch (e) { setError(errorMessage(e, 'Não foi possível carregar as categorias.')) } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  const save = async (name: string, categoryType: CategoryType) => { setBusy(true); try { if (editing === 'new') await api.post('/api/category/createCategory', { name, categoryType }); else if (editing) await api.put(`/api/category/updateCategory/${editing.id}`, { name, categoryType }); setEditing(null); await load() } catch (e) { setError(errorMessage(e, 'Não foi possível salvar a categoria.')) } finally { setBusy(false) } }
  const remove = async (item: Category) => { if (!window.confirm(`Excluir a categoria “${item.name}”?`)) return; try { await api.delete(`/api/category/deleteCategory/${item.id}`); await load() } catch (e) { setError(errorMessage(e, 'Não foi possível excluir a categoria.')) } }
  return <><PageTitle eyebrow="ORGANIZAÇÃO" title="Categorias" description="Agrupe entradas e despesas para entender melhor seus hábitos." action={<button className="button button-primary" onClick={() => setEditing('new')}><Plus size={17} /> Nova categoria</button>} />{error && <ErrorBox message={error} retry={() => void load()} />}
    {editing !== null && <section className="panel editor-panel"><div className="panel-heading"><div><h2>{editing === 'new' ? 'Nova categoria' : 'Editar categoria'}</h2><p>Defina um nome e os tipos de lançamento aceitos.</p></div></div><CategoryEditor key={editing === 'new' ? 'new' : editing.id} initial={editing === 'new' ? undefined : editing} onSave={save} onCancel={() => setEditing(null)} busy={busy} /></section>}
    <section className="panel management-panel"><div className="panel-heading"><div><h2>Suas categorias</h2><p>{categories.length} {categories.length === 1 ? 'categoria cadastrada' : 'categorias cadastradas'}</p></div></div>{loading ? <Loading /> : categories.length === 0 ? <EmptyState title="Organize suas movimentações" text="Crie categorias para classificar entradas e despesas." icon={Tags} action={<button className="button button-secondary" onClick={() => setEditing('new')}><Plus size={16} /> Criar categoria</button>} /> : <div className="category-list">{categories.map((category, index) => <article className="category-row" key={category.id}><span className={`category-symbol category-symbol-${index % 5}`}><Tags size={18} /></span><div className="category-info"><strong>{category.name}</strong><small>{categoryTypeName[category.categoryType]}</small></div><span className={`pill ${category.categoryType === 'ENTRY' ? 'pill-income' : category.categoryType === 'EXIT' ? 'pill-expense' : 'pill-neutral'}`}>{categoryTypeName[category.categoryType]}</span><div className="row-actions"><button className="icon-button" aria-label={`Editar ${category.name}`} onClick={() => setEditing(category)}><Pencil size={15} /></button><button className="icon-button danger-icon" aria-label={`Excluir ${category.name}`} onClick={() => void remove(category)}><Trash2 size={15} /></button></div></article>)}</div>}</section></>
}

const categoryTypeName: Record<CategoryType, string> = { ENTRY: 'Entrada', EXIT: 'Despesa', BOTH: 'Ambos' }
const frequencies: Frequency[] = ['WEEKLY', 'MONTHLY', 'QUARTERLY', 'SEMIANNUAL', 'ANNUAL']
const frequencyName: Record<Frequency, string> = { WEEKLY: 'Semanal', MONTHLY: 'Mensal', QUARTERLY: 'Trimestral', SEMIANNUAL: 'Semestral', ANNUAL: 'Anual' }
const brDate = (value: string) => new Intl.DateTimeFormat('pt-BR').format(new Date(`${value}T12:00:00`))

function SubscriptionEditor({ categories, initial, onSave, onCancel, busy }: { categories: Category[]; initial?: Subscription; onSave: (form: { name: string; value: string; frequency: Frequency; startDate: string; categoryId: string }) => Promise<void>; onCancel: () => void; busy: boolean }) {
  const expenseCategories = categories.filter((category) => category.categoryType === 'EXIT' || category.categoryType === 'BOTH')
  const [form, setForm] = useState({ name: initial?.name ?? '', value: initial ? String(initial.value) : '', frequency: initial?.frequency ?? 'MONTHLY' as Frequency, startDate: initial?.startDate ?? '', categoryId: initial ? String(initial.categoryTypeId) : '' })
  return <form className="edit-form" onSubmit={(event) => { event.preventDefault(); void onSave(form) }}><div className="form-grid"><label className="field"><span>Nome</span><input required maxLength={100} value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Ex.: Internet, academia…" /></label><label className="field"><span>Valor</span><input type="number" required min="0.01" step="0.01" value={form.value} onChange={(event) => setForm({ ...form, value: event.target.value })} placeholder="0,00" /></label><label className="field"><span>Frequência</span><select value={form.frequency} onChange={(event) => setForm({ ...form, frequency: event.target.value as Frequency })}>{frequencies.map((frequency) => <option key={frequency} value={frequency}>{frequencyName[frequency]}</option>)}</select></label><label className="field"><span>Data de início</span><input type="date" required value={form.startDate} onChange={(event) => setForm({ ...form, startDate: event.target.value })} /></label><label className="field"><span>Categoria de despesa</span><select required value={form.categoryId} onChange={(event) => setForm({ ...form, categoryId: event.target.value })}><option value="">Selecione uma categoria</option>{expenseCategories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label></div>{expenseCategories.length === 0 && <p className="inline-note">Crie uma categoria de despesa antes de adicionar uma assinatura.</p>}<p className="inline-note">A API registra a frequência e a próxima cobrança; ela não lança despesas automaticamente.</p><div className="form-actions"><button type="button" className="button button-quiet" onClick={onCancel}>Cancelar</button><button className="button button-primary" disabled={busy || expenseCategories.length === 0}>{busy ? 'Salvando…' : initial ? 'Salvar alterações' : 'Adicionar assinatura'}</button></div></form>
}

export function SubscriptionsPage() {
  const [subscriptions, setSubscriptions] = useState<Subscription[]>([])
  const [categories, setCategories] = useState<Category[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [editing, setEditing] = useState<Subscription | 'new' | null>(null)
  const [busy, setBusy] = useState(false)
  const load = useCallback(async () => { setLoading(true); try { const [subs, cats] = await Promise.all([api.get<Subscription[]>('/api/subscription/listSubscriptions'), api.get<Category[]>('/api/category/categoriesList')]); setSubscriptions(subs.data); setCategories(cats.data); setError('') } catch (e) { setError(errorMessage(e, 'Não foi possível carregar as assinaturas.')) } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  const save = async (form: { name: string; value: string; frequency: Frequency; startDate: string; categoryId: string }) => { setBusy(true); try { const body = { name: form.name.trim(), value: Number(form.value), frequency: form.frequency, startDate: form.startDate }; if (editing === 'new') await api.post(`/api/subscription/createSubscription/${form.categoryId}`, body); else if (editing) await api.put(`/api/subscription/updateSubscription/${editing.id}/${form.categoryId}`, body); setEditing(null); await load() } catch (e) { setError(errorMessage(e, 'Não foi possível salvar a assinatura.')) } finally { setBusy(false) } }
  const remove = async (item: Subscription) => { if (!window.confirm(`Excluir a assinatura “${item.name}”?`)) return; try { await api.delete(`/api/subscription/deleteSubscription/${item.id}`); await load() } catch (e) { setError(errorMessage(e, 'Não foi possível excluir a assinatura.')) } }
  const activeTotal = subscriptions.filter((item) => item.subscriptionStatus === 'ACTIVE').length
  return <><PageTitle eyebrow="DESPESAS RECORRENTES" title="Assinaturas" description="Acompanhe valores, frequência e próximas cobranças cadastradas." action={<button className="button button-primary" onClick={() => setEditing('new')}><Plus size={17} /> Nova assinatura</button>} />{error && <ErrorBox message={error} retry={() => void load()} />}
    <div className="subscription-summary"><div className="summary-icon"><CreditCard size={19} /></div><div><span>Assinaturas ativas</span><strong>{activeTotal}</strong></div><small>A API registra os cadastros e a próxima cobrança; não cria transações automaticamente.</small></div>
    {editing !== null && <section className="panel editor-panel"><div className="panel-heading"><div><h2>{editing === 'new' ? 'Nova assinatura' : 'Editar assinatura'}</h2><p>Cadastre um compromisso recorrente.</p></div></div><SubscriptionEditor key={editing === 'new' ? 'new' : editing.id} categories={categories} initial={editing === 'new' ? undefined : editing} onSave={save} onCancel={() => setEditing(null)} busy={busy} /></section>}
    <section className="panel management-panel"><div className="panel-heading"><div><h2>Seus compromissos</h2><p>Próximas cobranças previstas no cadastro</p></div></div>{loading ? <Loading /> : subscriptions.length === 0 ? <EmptyState title="Nenhuma assinatura cadastrada" text="Adicione suas despesas recorrentes para acompanhar quando elas vencem." icon={CreditCard} action={<button className="button button-secondary" onClick={() => setEditing('new')}><Plus size={16} /> Adicionar assinatura</button>} /> : <div className="subscription-list">{subscriptions.map((item) => <article className="subscription-card" key={item.id}><div className="subscription-heading"><span className="subscription-glyph"><CreditCard size={18} /></span><div><strong>{item.name}</strong><small>{item.categoryTypeName} · {frequencyName[item.frequency]}</small></div><span className={`pill ${item.subscriptionStatus === 'ACTIVE' ? 'pill-income' : 'pill-neutral'}`}>{item.subscriptionStatus === 'ACTIVE' ? 'Ativa' : 'Cancelada'}</span></div><div className="subscription-details"><div><span>Valor cadastrado</span><strong>{money(item.value)}</strong></div><div><span>Próxima cobrança</span><strong>{brDate(item.nextCharge)}</strong></div><div><span>Início</span><strong>{brDate(item.startDate)}</strong></div><div className="row-actions"><button className="icon-button" aria-label={`Editar ${item.name}`} onClick={() => setEditing(item)}><Pencil size={15} /></button><button className="icon-button danger-icon" aria-label={`Excluir ${item.name}`} onClick={() => void remove(item)}><Trash2 size={15} /></button></div></div></article>)}</div>}</section></>
}

export function ProfilePage() {
  const { user, refreshUser, signOut } = useAuth()
  const [form, setForm] = useState({ name: user?.name ?? '', email: user?.email ?? '', senhaHash: '' })
  const [message, setMessage] = useState('')
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  useEffect(() => { setForm((old) => ({ ...old, name: user?.name ?? '', email: user?.email ?? '' })) }, [user])
  const save = async (event: FormEvent) => { event.preventDefault(); setMessage(''); setError(''); setBusy(true); try { await api.put('/api/user/updateUser', form); await refreshUser(); setForm((old) => ({ ...old, senhaHash: '' })); setMessage('Perfil atualizado com sucesso.') } catch (e) { setError(errorMessage(e, 'Não foi possível atualizar o perfil.')) } finally { setBusy(false) } }
  const removeAccount = async () => { if (!window.confirm('Desativar sua conta? Você perderá acesso aos seus dados financeiros.')) return; try { await api.delete('/api/user/deleteUser'); signOut() } catch (e) { setError(errorMessage(e, 'Não foi possível desativar sua conta.')) } }
  return <><PageTitle eyebrow="SUA CONTA" title="Perfil e configurações" description="Gerencie os dados associados à sua conta." />{error && <ErrorBox message={error} />}{message && <div className="alert alert-success" role="status"><Check size={16} />{message}</div>}<section className="panel profile-panel"><div className="panel-heading"><div><h2>Informações pessoais</h2><p>O backend solicita uma nova senha ao salvar os dados do perfil.</p></div></div><form className="edit-form profile-form" onSubmit={(event) => void save(event)}><div className="profile-avatar-large">{user?.name.slice(0, 1).toUpperCase()}</div><div className="form-grid"><label className="field"><span>Nome</span><input required maxLength={100} value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label className="field"><span>E-mail</span><input type="email" required value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></label><label className="field"><span>Nova senha</span><input type="password" autoComplete="new-password" required minLength={8} value={form.senhaHash} onChange={(event) => setForm({ ...form, senhaHash: event.target.value })} placeholder="Mínimo de 8 caracteres" /></label></div><div className="form-actions"><button className="button button-primary" disabled={busy || form.senhaHash.length < 8}>{busy ? 'Salvando…' : 'Salvar perfil'}</button></div></form></section><section className="panel danger-zone"><div><h2>Desativar conta</h2><p>Seu acesso será encerrado. Essa ação não apaga os dados associados.</p></div><button className="button button-danger" onClick={() => void removeAccount()}>Desativar minha conta</button></section></>
}
